namespace Chroma.Core.Sdl.Source;

/// <summary>
/// The loop a solid was generated by, when it was.
/// </summary>
/// <param name="Span">The <c>for</c> keyword itself.</param>
/// <param name="Variable">
/// The name the loop counts on, so the message can name the loop by it. Null when the loop
/// declares nothing to count on — <c>for (;;)</c> — and the message then says "this loop".
/// </param>
/// <param name="Count">How many times the body ran.</param>
/// <remarks>
/// Provenance, like <see cref="SourceSpan"/>, and here for the same reason: a diagnostic
/// has to point at something a reader can act on. Every solid a loop emits shares one
/// <see cref="SourceSpan"/> — the body is written once — so a span budget blown by five
/// hundred generated spheres would otherwise be reported against a line that reads
/// perfectly well, five hundred times over. The loop is the thing to change.
/// </remarks>
public sealed record LoopOrigin(SourceSpan Span, string? Variable, int Count)
{
    /// <summary>How to refer to this loop in a sentence.</summary>
    public string Describe() => Variable is null ? "this loop" : $"this loop over '{Variable}'";
}
